# Generated by Django 3.1 on 2020-08-10 15:54

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Post image', upload_to='post_image/', verbose_name='Post image')),
                ('title', models.CharField(help_text='Input post title', max_length=200, verbose_name='Post title')),
                ('about', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
